### ISSUE TITLE
Can't import rpack_core on Blender 3.6

### ISSUE THREAD

**Issue by 77temp** [HerrWaffel/image-packer#1]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\templ\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\image-packer-master\__init__.py", line 12, in <module>
    from . import operators, properties, ui, preferences
  File "C:\Users\templ\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\image-packer-master\operators.py", line 4, in <module>
    from .utils import (
  File "C:\Users\templ\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\image-packer-master\utils.py", line 7, in <module>
    from .dependencies import rpack
  File "C:\Users\templ\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\image-packer-master\dependencies\rpack\__init__.py", line 146, in <module>
    from ._core import (
ModuleNotFoundError: No module named 'image-packer-master.dependencies.rpack._core'

**Comment by HerrWaffel** [comment]
Hey, thanks for bringing it to my attention.
Currently, I need help to make the addon work with the rpack dependency. So for now, I removed it from the addon.
